import sys
from inducers import toxtree_hERG
from inducers import toxtree_nav
 


def HELP():
	print("Please abide by the command format:\n\tpython toxtree.py -i <input_csv_file> [--hERG | --Nav1.5]\n\nWhere <input_csv_file> is the input file to the software. It has to include the 1444 1D and 2D descriptors generated by Padel. Whereas [--hERG | --Nav1.5] represents a tag to the command, specifying whether you want to make predictions for hERG or Nav1.5.")

if __name__ == "__main__":
	if len(sys.argv) == 2 and (sys.argv[1] == '--help' or sys.argv[1] == '-h'):
		HELP()
	elif len(sys.argv) != 4:
		HELP()
	else:
		if sys.argv[3] != '--hERG' and sys.argv[3] != '--Nav1.5':
			HELP()
		elif not sys.argv[2].endswith('.csv'):
			print('Please provide a CSV file Where the first row contains the feature labels and the following rows include the numerical values. Each row corresponds to a single molecular compound.')
		elif sys.argv[3] == '--hERG':
			toxtree_hERG.hERG_infer(sys.argv[2])
		else:
			toxtree_nav.Nav_infer(sys.argv[2])